### ISSUE TITLE
Stiff head

### ISSUE THREAD

**Issue by Ctakep** [IthanMendoza/Fresh-Moves#1]
My skins head is stuck in place like if you were looking left and the eye movement is bugged cause of it.

**Comment by bitmochibit** [comment]
This happens to me too, and I'm on the latest EMF and ETF version (fabric) and the head is backwards and looking to the left

**Comment by IthanMendoza** [comment]
So this must be some mod. I want both of you to tell me how the head gets stuck. I had a similar problem with paragliders mod and the body rotation. The body would get stuck in one rotation after using the paragilder.

**Comment by bitmochibit** [comment]
I remove all the mods I have (leaving only the necessaries of the resource pack) and it is like this
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/39531150/88c1813e-ddcc-4441-939d-ff62517861e6)

**Comment by IthanMendoza** [comment]
Is this fixed with the latest of EMF, ETF and Fresh Moves?
