### ISSUE TITLE
the lil creeper face in resouce packs isnt there

### ISSUE THREAD

**Issue by GloooGunner** [IthanMendoza/Fresh-Moves#10]
im trying to follow the tutorial for fixing black eyes but the creeper face from step 3 isnt showing up
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/168913484/c7677e55-3c4c-459f-b9dc-c9e27c4529fb)

**Comment by amykatname** [comment]
same

**Comment by amykatname** [comment]
this entity features mod setting shit dumb as hell, need to go in .minecraft\config\entity_texture_features.json

**Comment by GloooGunner** [comment]
thx i made it works now

**Comment by IthanMendoza** [comment]
I'm aware that some clients mess the with game's UI so it can be something like that.
