### ISSUE TITLE
please add axolotl eyes support

### ISSUE THREAD

**Issue by lightnignmc09** [IthanMendoza/Fresh-Moves#11]
I have weird eyes, as my skin is an axolotl. could you add the pupils eyes for an axolotl (very outer pixels, wraps around to sides)
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/81399992/6453ab4f-30ba-4161-9ab9-0b73098e6ac2)
thanks in advance!

**Comment by IthanMendoza** [comment]
I'll add more eye compat in the future but I'll need to pick which of them I will add (with a survey) I'll take those in count.
