### ISSUE TITLE
black face :,(

### ISSUE THREAD

**Issue by V01DW3B** [IthanMendoza/Fresh-Moves#12]
i did everything that was in that video it didint help 
![2024-05-04_17 30 23](https://github.com/IthanMendoza/Fresh-Moves/assets/68392877/1335c5c4-020c-401f-aaa2-2e7a6993c737)
1. used in picture ^
![V01DW3B Anim Skin (1)](https://github.com/IthanMendoza/Fresh-Moves/assets/68392877/5a5e7c92-0563-4481-be35-59cb3fc41a66)
2.
![V01DW3B Anim Skin](https://github.com/IthanMendoza/Fresh-Moves/assets/68392877/e3e4d50a-ccb9-42a6-a375-c6c4ae5c839f)

**Comment by V01DW3B** [comment]
fixed

**Comment by Quizer9O8** [comment]
> fixed

`I am also experiencing the same issue. How did you fix this?

**Comment by ALEKSCRAFTPLAY** [comment]
> > fixed
> 
> I am also experiencing the same issue. How did you fix this?

Read the texture pack description about the black thing and there will be an solution
