### ISSUE TITLE
What about the pig skin?

### ISSUE THREAD

**Issue by Xryn228** [IthanMendoza/Fresh-Moves#13]
I am Hryun, or rather Hryun is my character and I naturally have a pig skin in Minecraft, like most of the Minecraft community, but there are no instructions that would show the exact location of the eyes, which are located on the fifth pixel along the edges of the face. I would like to use this mod, but I can't use it due to this reason

**Comment by IthanMendoza** [comment]
I'll add more eye compat in a future but I need to select which of those I'm gonna add (in survey) because I don't have much space left in the skin.png to use. I'll take those in count
