### ISSUE TITLE
Two Eyes Issue

### ISSUE THREAD

**Issue by KingBeast148** [IthanMendoza/Fresh-Moves#137]
I'm experiencing a glitch where two eyes are appearing. I'm not sure if it's due to a mistake I had made with the settings or the skin, or if it's an issue with the mod itself.

Thanks In Advanced. - KB

Here's a screenshot of the two eyes and PNG of the skin: 
![Screenshot 2024-07-25 085404](https://github.com/user-attachments/assets/cf421771-9773-4d05-abe4-284bfb597a47)
![8398685e3856d62590f909cf93da5426cba5d7cc](https://github.com/user-attachments/assets/30440209-c470-4fc6-b456-7b50b0469b30)

**Comment by KingBeast148** [comment]
I Managed to fix the issue. For anyone wondering I just made a mistake.

**Comment by Enastr** [comment]
May I ask how you solved it? I'm having the same problem
