### ISSUE TITLE
top 1x2 eyes dont blink

### ISSUE THREAD

**Issue by GloooGunner** [IthanMendoza/Fresh-Moves#14]
i tried with bottom 1x2 and they work so i dont think theres anything wrong with my mods

**Comment by IthanMendoza** [comment]
Can you send the edited skin?

**Comment by GloooGunner** [comment]
> Can you send the edited skin?

yea sure
![2021_09_04_glue-gunner--btd6--18838144](https://github.com/IthanMendoza/Fresh-Moves/assets/168913484/756e5927-0368-4da9-8c1b-259ecb24dccb)

**Comment by GloooGunner** [comment]
ok so i decided to use 2x2 eyes instead and it looks really good

https://github.com/IthanMendoza/Fresh-Moves/assets/168913484/fff67497-263c-4e46-88ef-b0559deba81a

**Comment by IthanMendoza** [comment]
Yep they told me that on the server too
will get fixed soon

**Comment by HackMeMan** [comment]
If your problem is resolved, it's usually a good idea to close the issue, unless the solution was an unintended workaround.
