### ISSUE TITLE
a plugin for editing eyes in blockbench! + make a jump animation?

### ISSUE THREAD

**Issue by BussyBakks** [IthanMendoza/Fresh-Moves#149]
all i want is on title pls 😭

**Comment by BussyBakks** [comment]
@IthanMendoza

**Comment by TheDrawingCoder-Gamer** [comment]
In blockbench you can view the model and play the animation but its kind of cursed (i don't really get it.)
1. Install CEM Template Loader
2. Install EMF Animation Addon
3. Download player.jem or player_slim.jem from this repo (here https://github.com/IthanMendoza/Fresh-Moves/tree/main/assets/minecraft/optifine/cem)
4. Open it in blockbench, find the "Animation Editor" pane and fix line 24 (add `== 1` after the `var.skydive` test)
5. you SHOULD be able to view animations now with the play button and animation controller

TBH idk if this fully works; for me the eyebrows on my skin are currently broken and don't display

**Comment by TheDrawingCoder-Gamer** [comment]
nah you have to use the player.jem/player_slim.jem from the resource pack zip file. this repo has incorrect file

**Comment by BussyBakks** [comment]
> In blockbench you can view the model and play the animation but its kind of cursed (i don't really get it.)
> 
> 1. Install CEM Template Loader
> 2. Install EMF Animation Addon
> 3. Download player.jem or player_slim.jem from this repo (depending on skin type) (here https://github.com/IthanMendoza/Fresh-Moves/tree/main/assets/minecraft/optifine/cem)
> 4. Open it in blockbench, find the "Animation Editor" pane and fix line 24 (add `== 1` after the `var.skydive` test)
> 5. you SHOULD be able to view animations now with the play button and animation controller
> 
> TBH idk if this fully works; for me the eyebrows on my skin are currently broken and don't display

@TheDrawingCoder-Gamer it so confusing, i followed in wiki and draw with .jem animation file, it confused (i changed my skin to bottom2x2)

**Comment by BussyBakks** [comment]
![image](https://github.com/user-attachments/assets/18e75c2c-cff6-4289-ad5e-ee423335376b)
like this

**Comment by BussyBakks** [comment]
if i follow the wiki, it not animate yet

**Comment by BussyBakks** [comment]
augh it just cant animate in blockbench, import to MC still works (follow Wiki) so issue done!

**Comment by BussyBakks** [comment]
![image](https://github.com/user-attachments/assets/cd7d59e1-4374-4185-87f3-9d2be7771a7b)
![image](https://github.com/user-attachments/assets/9d260586-658f-460e-939d-56e8c4b70799)
some tests
