### ISSUE TITLE
What eyebrows are needed for upper Mid 2x1 eyes?

### ISSUE THREAD

**Issue by Vavun33** [IthanMendoza/Fresh-Moves#17]
I tried to animate the skin, but for some reason I always had problems with either the eyes or the eyebrows...

**Comment by Vavun33** [comment]
If it’s not difficult, how to make an animation for this:
!(https://github.com/IthanMendoza/Fresh-Moves/assets/121681870/dd58af36-06da-4c28-81a2-f360d587dda7)

**Comment by IthanMendoza** [comment]
This one 
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/3939bcfb-3ca3-4a50-bbb2-bb8c2e772f38)

**Comment by IthanMendoza** [comment]
This one 
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/c18af061-f6fe-4f1c-b86e-e63347241b5b)

**Comment by Vavun33** [comment]
Everything was done according to the instructions:
![Screenshot 2024-05-05 103430](https://github.com/IthanMendoza/Fresh-Moves/assets/121681870/9ce08597-2020-4cab-8fd2-cf382d955a7a)
![95b6da5674194578 (1)](https://github.com/IthanMendoza/Fresh-Moves/assets/121681870/c0724f05-4fe3-4411-b75f-64c3c30a4294)

**Comment by IthanMendoza** [comment]
You put them too high. This is the correct positions:
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/8f846866-9f62-4abb-a04f-e1dd66bda2b7)
