### ISSUE TITLE
[Bug] Incompatability Between Fresh Moves Resourcepack and MoreCulling

### ISSUE THREAD

**Issue by CannedDumby** [IthanMendoza/Fresh-Moves#18]
Tested with and without MoreCulling, when in the inventory, the paper doll (player) will become transparent according to whatever direction the mouse is pointing. I'm fairly certain it something to do with EMF, but i thought i'd put up a notice here as well

![2024-05-04_16 54 10](https://github.com/IthanMendoza/Fresh-Moves/assets/113647758/4c9bf3f1-e737-4030-b519-338c3f8112f5)

**Comment by IthanMendoza** [comment]
Interesting. A guy in the comments section already had this answer some time ago

![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/2b8ebd01-258c-4e7e-8bf5-ff09bdddb358)

**Comment by CannedDumby** [comment]
That's great to know, actually.
