### ISSUE TITLE
Are these types of eyes supported?

### ISSUE THREAD

**Issue by Lexian-droid** [IthanMendoza/Fresh-Moves#19]
Hello, I had my skin made as a commission, and they did feminine eyelashes:
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/83799577/db5c29e6-c1e6-48a0-a328-ef4659d70384)

how would I go about adding them if it's possible?

**Comment by IthanMendoza** [comment]
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/468f03cd-e0f1-4408-b6fa-eec668e8336c)
Does this skin fit that preset?

**Comment by IthanMendoza** [comment]
you can just not put the bottom dark green and orange pixels

**Comment by Lexian-droid** [comment]
Ah yes, those are it! Thanks a lot! Sorry I didn't realize they were Eyelashes.
