### ISSUE TITLE
Player Model Head turned around

### ISSUE THREAD

**Issue by ThatFoxgirl** [IthanMendoza/Fresh-Moves#2]
So idk what happened but when I tried the Fresh Moves (EMF Player Animation) Resource Pack with the included Mods and set up my Character and uploaded it on Minecraft it keeps on breaking every time when I try to use it in a World. The animations work and the eyes blink like they are supposed to, not in the right spot but that's a me issue, tho the Player Head is completely turned around and whacky and idk why.
![2024-04-28_02 05 50](https://github.com/IthanMendoza/Fresh-Moves/assets/168313735/bda02c80-eab1-4169-b33c-22feae6f32ac)
![2024-04-28_02 05 55](https://github.com/IthanMendoza/Fresh-Moves/assets/168313735/f20ee7be-afd6-4dcd-a0a3-362caaf65af8)

**Comment by ThatFoxgirl** [comment]
I tried it out in a new test Pack with only the EMF, ETF, CSL Mods and Fresh Moves Resource Pack. It works fine there so it has to be a Mod complication that messes up the Player's Head. I just don't know which Mod it is.

**Comment by IthanMendoza** [comment]
Are you using a modpack? I want to know what mod could cause that

**Comment by ThatFoxgirl** [comment]
Yes I'm using a Modpack. I use the Better MC [Fabric] 1.20.1 Modpack with Fabric 0.15.0
I already removed the mods: 3D Skins, Luna, BisectHosting Server Integration Menu, Drippy Loading Screen and Fancy Menu from the Modpack

**Comment by ThatFoxgirl** [comment]
I can also already approve of Essential not being the Mod that breaks the Skin. In my Test Pack I also added Essential and it worked fine.

**Comment by IthanMendoza** [comment]
I changed the head rotation limitation. Is this fixed. I haven't been able to replicate it.

**Comment by ThatFoxgirl** [comment]
That fixed it! Thanks
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/168313735/8bda405e-6886-452a-8859-f06361935703)
