### ISSUE TITLE
Ears Compatability

### ISSUE THREAD

**Issue by Oliver-makes-code** [IthanMendoza/Fresh-Moves#20]
[Ears](https://modrinth.com/mod/ears) is a mod that adds extra skin features to the player model, used for furry skins.
Since it uses the skin texture to store it's data, it's incompatible with this.
I was wondering if there's a way to make it compatible.

**Comment by IthanMendoza** [comment]
I don't know if there's a way I could make it work

**Comment by IthanMendoza** [comment]
They conflict in the way they add their features so there's not much I can do
