### ISSUE TITLE
Emotecraft + Just expressions.

### ISSUE THREAD

**Issue by VantiBunny** [IthanMendoza/Fresh-Moves#21]
Just find out how to make Just Expressions work with Emotecraft.

Simply delete body parts in player.jem and player_slim.jem file.

.\assets\minecraft\optifine\cem then scroll down to "part": "body" and delete everything. Should be looking like this:

![image](https://github.com/IthanMendoza/Fresh-Moves/assets/134135482/57f604ab-4b9f-40d2-9978-0119c78f09fb)

**Comment by Vavun33** [comment]
Is it possible to make Emotecraft work with Fresh Moves?

**Comment by VantiBunny** [comment]
No, Emotecraft use own part system that have bend parts.

**Comment by VantiBunny** [comment]
> Is it possible to make Emotecraft work with Fresh Moves?

No. Emotecraft use their own parts system that have bends.
