### ISSUE TITLE
Outer Skin Layer way messed up

### ISSUE THREAD

**Issue by NotPyro404** [IthanMendoza/Fresh-Moves#223]
First thought issue was 3D skin layers, but had no issues before. Disabled pack and went back to normal just without the animation (duh.) Assuming Pack isnt updated to 1.21.4 yet is the issue, or if that's just 1 issue of a few.
![image](https://github.com/user-attachments/assets/13ebcaf3-9a30-450c-9e24-6eca83a5cd1a)

**Comment by NotPyro404** [comment]
(same issue as #215)

**Comment by SonaSudebta** [comment]
refer to #222 
ClaraTheRed's version works on mine

**Comment by ahmed4363** [comment]
I'm pretty sure this is a problem with EMF, they changed something in 1.21.2 and that broke skin layers
[I'm pretty sure it's this change](https://github.com/Traben-0/Entity_Model_Features/blob/master/.github/1.21.2%2B%20%20changes.md#player-models)

**Comment by ClaraTheRed** [comment]
As @SonaSudebta mentioned, I have a fork here with changes from @erinsc who made the fix, together with animation fixes from me https://github.com/ClaraTheRed/Fresh-Moves

**Comment by Mariolazer1** [comment]
How do i implement the fork?

**Comment by ClaraTheRed** [comment]
You can download the resource pack here https://github.com/ClaraTheRed/Fresh-Moves/archive/refs/heads/main.zip

It includes both the version with the expressive eyes and the one without.
