### ISSUE TITLE
Feature Request: Monocular vision layout?

### ISSUE THREAD

**Issue by CrackheadHarry** [IthanMendoza/Fresh-Moves#23]
Is there/Will there be support for eyes placed on the sides rather than the front of the head like this? 
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/29113836/b02f4bb4-2c9d-4bcf-a6a9-272c0d86a295)

**Comment by IthanMendoza** [comment]
interesting but I cannot promise anything
