### ISSUE TITLE
Feature Request: Slime Type Eyes

### ISSUE THREAD

**Issue by Novampr** [IthanMendoza/Fresh-Moves#24]
You can get Slime type eyes by removing the pupils in the image but it leads to some weird eyes, so I suggest that there is a slime eye type (2x2 as that's how slimes are)

For example this is how it looks when you look up:
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/100384210/0a1bb48a-1384-40e4-9ef4-2beb34ef22b9)

**Comment by IthanMendoza** [comment]
I won't probably add these. The space has become limited in the skin
