### ISSUE TITLE
Feature request: Moving 1x1 eyes

### ISSUE THREAD

**Issue by stefshortboi** [IthanMendoza/Fresh-Moves#25]
Will movement be added to the 1x1 eyes? Right now there is only the eyelids but I would love to see the same eye functionality of the 2x1/3x1 eyes get added to the 1x1 eyes. I have however found a workaround by using the 2x1 eyes and making the eye-white the color of my skin, but I would love to see this as a default thing when you use the 1x1 eyes.

**Comment by IthanMendoza** [comment]
I try to remaing somewhat similar to fresh animations with the eye stuff. Piglins also have an eye that is a single pixel but they just have a blinking animatio, so I don't think I'll add something like 1x1 moving eyes
