### ISSUE TITLE
2x3 Positions

### ISSUE THREAD

**Issue by CoBehOKjar** [IthanMendoza/Fresh-Moves#28]
Are there other 2x3 eye positions or just one? I would like to animate eyes like this
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/60312685/cb9ec3b2-b182-4bae-b54b-88c75c7f9fe9)

**Comment by IthanMendoza** [comment]
I plan more offsets of multiple eyes in a future update. I may have to move some stuff in the current ones.

**Comment by CoBehOKjar** [comment]
it looks even better than I expected
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/60312685/c337758e-7d25-4c0f-9ed8-21787475e6f8)
 

https://github.com/IthanMendoza/Fresh-Moves/assets/60312685/dcffaba7-110d-43b7-94f6-688092d82845

**Comment by IthanMendoza** [comment]
more 2x3 will come in future updates
