### ISSUE TITLE
Possible improvement to eye placement method

### ISSUE THREAD

**Issue by Obturo** [IthanMendoza/Fresh-Moves#29]
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/102693799/2ee5bf8f-8460-4d26-b956-7e47985774f3)

I'm don't fully understand how you are converting the different eye behaviours into animations but, i noticed that when making any features it was pretty limited in the dimensions without more hard-coding which would  limit the number of different eyes you could have.

I don't know whether it's possible but would using the [**left** purple and orange areas in the photo] as a way to tell which eye [purple] and eyebrow [orange] behaviours to use. Using the position of a painted pixel to detemine the behaviour:
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/102693799/64a40dc4-b0d8-476e-80fa-5c7324bbe645)

(It would be similar for the eyebrows but you would use one pixel as a boolean to determine if they should be displayed over the second layer)

The [**right** purple and orange areas] could then be used to define the eyes anywhere on the face or even if the behaviour selected is correct define eyes on the side of the face that can then be mirrored?

I'm not to sure how the eyelids work as you add them to the eyes and the eyebrows but, their location and colour could be defined in the [blue on the right] and their behaviour matches the eyes behaviour?

Anyway just an idea i thought i'd suggest, i'm not sure if it's possible 🤷‍♂️

**Comment by IthanMendoza** [comment]
Yeah I was thinking something like that If I made Fresh Moves a mod instead. But for the time being reality is a little more boring.
The animated eyes are just invisible cubes that are waiting to have a texture so they can become visible to the human eye. They are always there (also the reason of the black eyes problem)
