### ISSUE TITLE
Upper Body swaying back and forth in 3.0

### ISSUE THREAD

**Issue by Yoota2** [IthanMendoza/Fresh-Moves#3]
So I wanted to try out the mod since i saw a [video](https://www.youtube.com/watch?v=uEyeM7gB8NQ) about it. 
I made a profile on modrinth and downloaded the mods and such.
![grafik](https://github.com/IthanMendoza/Fresh-Moves/assets/157834328/7be87e8a-18fa-4bf2-9676-8962f219de3b)
(i hope the screenshot uploaded correctly) 
The upper body starts moving back and forth when standing still, other animations dont seem to be affected.

https://github.com/IthanMendoza/Fresh-Moves/assets/157834328/1dd691c8-3a78-4c35-a4bb-02ae3e0b9f39

Version 2.3 works fine, only 3.0 has this issue

**Comment by Yoota2** [comment]
To add, I've now installed [Custom skin loader](https://modrinth.com/mod/customskinloader) and the eyes are working fine. I've also adjusted the ETF/EMF settings according to the [Fresh Moves site](https://modrinth.com/resourcepack/tras-fresh-player) and the eyes are working. The issue persists though. 

https://github.com/IthanMendoza/Fresh-Moves/assets/157834328/6b75ce5b-1779-46fc-b30e-f50733d012e0

**Comment by IthanMendoza** [comment]
Sorry for that issue, I think it's now fixed in 3.0.1

**Comment by Yoota2** [comment]
> Sorry for that issue, I think it's now fixed in 3.0.1

Yep that fixed it, thank you and keep it up, this resource pack is awesome
