### ISSUE TITLE
Feature Request: eyelashes for 2x2 eyes 3 pixels from below

### ISSUE THREAD

**Issue by TheRubyGames** [IthanMendoza/Fresh-Moves#30]
I cannot seem to find a way to get eyelashes for my 2x2 eyes. There is a location for eyebrows but not eyelashes. I would like to know if this is possible. Thank you
![image_2024-05-05_194252604](https://github.com/IthanMendoza/Fresh-Moves/assets/107088748/4cb872da-a313-4cac-a16e-6bfb8206711d)

**Comment by IthanMendoza** [comment]
Not for the time being. I may add one more offset for the eyelashes but those won't have such high position.
