### ISSUE TITLE
Feature Request: 4x1eyes

### ISSUE THREAD

**Issue by JustJabka** [IthanMendoza/Fresh-Moves#32]
I was going to use this resource pack to get the blinking eyes for my skin with a 4x1eye set and noticed that neither of them supported the eye set that I have on my skin. If this is to specific to ask for I'd understand. Sorry for taking up your time
![skin head](https://github.com/IthanMendoza/Fresh-Moves/assets/117545035/824d202c-5162-4f09-b81a-4f03bcf46afb)

**Comment by IthanMendoza** [comment]
I already have tons of eye shapes request and little space left on the skin (without using ETF's skin features space like emmisives) . I can just add some of them in future updates. I may do a survey for that. I'll take those in consideration
