### ISSUE TITLE
An arrow stuck in the head is not displayed correctly

### ISSUE THREAD

**Issue by JustJabka** [IthanMendoza/Fresh-Moves#33]
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/117545035/be3ad751-0541-441a-814d-88cbeeeb3fdb)
A skeleton shot me in the head, but for some reason the arrow is in the air.

**Comment by stefshortboi** [comment]
I don't think this had anything to do with the resource pack

**Comment by Novampr** [comment]
I believe it is, I noticed the same thing after I applied the RP, however it could be the new mods

**Comment by IthanMendoza** [comment]
I don't think that there is something in the model causing this I wasn't able to replicate. I may take a look to the animation code nonetheless
