### ISSUE TITLE
Legs and arms are unsynced

### ISSUE THREAD

**Issue by abidbmt** [IthanMendoza/Fresh-Moves#34]
While walking, the legs and arms are unsynced making the walking animation look really unnatural once the left arm and left leg are suddenly perpendicular

![Bild_2024-05-07_150524210](https://github.com/IthanMendoza/Fresh-Moves/assets/62698817/c474e9ab-4d06-458a-bf4b-3eac013a7d29)

**Comment by IthanMendoza** [comment]
Yeah leg animations are independant fo arm movement (which is completely vanilla) I'll have to search for a way to sinchronize those 2
