### ISSUE TITLE
Feature Request: 3x1 Eyebrows & 2x1 Pupils

### ISSUE THREAD

**Issue by endcollector** [IthanMendoza/Fresh-Moves#35]
I'm sure you have many requests for new eye types, but I just wanted to throw my hat into the ring for 3x1 eyebrows and the possibility of having 2x1 pupils for many eye types. I've made a modified version of the resource pack that took me around 10 minutes that is for my use. I repurposed the Enderman eyes and one of the eyebrow types. 

I have attached a video of my skin using the modified pack which adds clarity to my explanations:

https://github.com/IthanMendoza/Fresh-Moves/assets/94948933/4b237699-b1be-41bf-b3b3-075ec34390ea

**Comment by IthanMendoza** [comment]
Wider pupils are not planned. mostly because I'm running out of space. I'm considering adding one more eyebrow offset and extending those 1 more pixel outwards.
