### ISSUE TITLE
Villager eyebrows not working 

### ISSUE THREAD

**Issue by Anvil58** [IthanMendoza/Fresh-Moves#37]
I did it as it says on the page.
Am i doing something wrong ?
![Clip](https://github.com/IthanMendoza/Fresh-Moves/assets/107875716/85b382f8-7449-4972-94ee-e909d5448835)

**Comment by IthanMendoza** [comment]
Are you using the correct pack
Is the Expressive.zip not Eyeless.zip

**Comment by Anvil58** [comment]
Yes i am using Expreesive

**Comment by IthanMendoza** [comment]
did you upload that modified skin.png to your account?

**Comment by Anvil58** [comment]
no i used essential
