### ISSUE TITLE
First Person Model & Essential compatibility

### ISSUE THREAD

**Issue by ITM-WAY** [IthanMendoza/Fresh-Moves#38]
I pretty much always play with theses two mods and I absolutely love the animations done with the pack!
When I try to play with the essential cosmetics the hat obstructs my view quite a bit. I included First Person Model as an issue  because the hat in the way does not occur wile disabled.
Will that be something you are thinking about fixing?
Also the 2x1 eyes but one pixel outwards, and maybe down?
![2024-05-07_21 38 44](https://github.com/IthanMendoza/Fresh-Moves/assets/169225804/bcc3312f-744d-4c19-9691-822e1f13d0b4)
![2024-05-07_21 38 47](https://github.com/IthanMendoza/Fresh-Moves/assets/169225804/32091c15-4b83-4746-90d8-f01c40b806b8)
![2024-05-07_21 39 02](https://github.com/IthanMendoza/Fresh-Moves/assets/169225804/e0d94738-e4a3-492c-8652-c55be4339db9)

**Comment by IthanMendoza** [comment]
This more seems like an issue from the first person camera you are using. I'm aware that real camera still renders the second layer of the head.
