### ISSUE TITLE
Body still disconnected

### ISSUE THREAD

**Issue by IFeuerKralle** [IthanMendoza/Fresh-Moves#39]
After the Update from the mod Essentials the body is now diconnected from the legs... again I guess.
![Bild_2024-05-08_103941585](https://github.com/IthanMendoza/Fresh-Moves/assets/135426356/393cc2f6-1c28-41a9-8bbb-5a8f245bc7a1)
Need help. Dont know what to do.

**Comment by IthanMendoza** [comment]
Legs and body entire position wont follow with these emotes, may come for a solution in some point
