### ISSUE TITLE
incompatibility with emote craft and custom emotes

### ISSUE THREAD

**Issue by timkofey** [IthanMendoza/Fresh-Moves#4]
When using some emotes legs are static or in waking animation when moving
<img width="675" alt="Screenshot 2024-05-02 at 12 15 02" src="https://github.com/IthanMendoza/Fresh-Moves/assets/116946984/b6a2ce74-1876-429c-b05d-67e427fb5f63">
<img width="362" alt="Screenshot 2024-05-02 at 12 15 35" src="https://github.com/IthanMendoza/Fresh-Moves/assets/116946984/ddcbfb49-58b6-4ec9-bea7-fbd72dc621ca">

<img width="712" alt="Screenshot 2024-05-02 at 12 15 57" src="https://github.com/IthanMendoza/Fresh-Moves/assets/116946984/40cc191a-6f68-4d0c-8dad-fd143fa5efb5">
<img width="408" alt="Screenshot 2024-05-02 at 12 15 43" src="https://github.com/IthanMendoza/Fresh-Moves/assets/116946984/d1c0400f-0648-4a1b-a381-b0a67e685dfe">

**Comment by IthanMendoza** [comment]
The current version overrides and doesn't allow other legs animations to play. I tried to fix this in v3.0 but it caused a body disconnection issue that made us to archive the v3.0 to fix it in v3.0.1. I still don't know if there's a proper way to make this compat without breaking the resource pack, but this is in the to do list.

**Comment by IthanMendoza** [comment]
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/077da239-9f8f-414d-afa7-8bbcdcf5ea3e)
what mod causes this XDDD?

**Comment by timkofey** [comment]
> ![image](https://private-user-images.githubusercontent.com/127630637/327600547-077da239-9f8f-414d-afa7-8bbcdcf5ea3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzA5MzksIm5iZiI6MTcxNDczMDYzOSwicGF0aCI6Ii8xMjc2MzA2MzcvMzI3NjAwNTQ3LTA3N2RhMjM5LTlmOGYtNDE0ZC1hZmE3LThiYmNkY2Y1ZWEzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMDAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTk4YTFmNTRlNjY0N2VkYjI0MTM3YmJjMjM4NTIyYzYyMjM4ZWZlOTZjYTgwODg1MDU4NzBkNzFhNGI1MDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F9bcN4PRez5xdmmOccsO1kyJnXCYPNyRsbcKqzOFXKk) what mod causes this XDDD?

It just another emote but the second image is the same emote but with pack

**Comment by Rail-TH** [comment]
As I noticed, the incompatibility with emotecraft hasn't been fixed yet. I support solving this problem, at absolutely any cost, even remaking the resourcepack into a mod, or making a separate version as a mod that will fix this. Why am I saying this? Dudes, no mod or resourcepack has animations this good

**Comment by SSJ3Bane** [comment]
Yeah I really need emotecraft and emf stuff working together ;-; no idea what else might fail because of this

**Comment by Khikki** [comment]
I support the message above! :)
