### ISSUE TITLE
outer eyes and derp eyes that work like normal eyes?

### ISSUE THREAD

**Issue by hellbackTNT** [IthanMendoza/Fresh-Moves#40]
so i was trying too get the eyes working (i did but it looked cursed) but i notised that there where no outer eyes for skins like mine. it would be great if there was outer eyes.
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/156220229/6671cd30-7f68-4ea9-953a-27d2bdee98c9)
and as you see on my skin, my eyes are like derp eyes. but i dont want them to behave like them when fixing the eyes. would there be a way to have them work like normal eyes but for other people they look like normal?

**Comment by IthanMendoza** [comment]
This type in particular comes from a mob and those will have their own section in a future update.
