### ISSUE TITLE
More animations

### ISSUE THREAD

**Issue by alturz2** [IthanMendoza/Fresh-Moves#41]
This is a really nice mod, but It would be nice to see some more animations. Specifically:
- More animations for when the player is in water (floating) and better swimming animations. Examples of what i mean (0:09-0:18) - https://www.youtube.com/watch?v=In76USxVFPQ. The bed animation in the video is quite cool too
- player falling animations
- better mining animation like https://www.youtube.com/watch?v=9AvJA891kck at the beginning

**Comment by IthanMendoza** [comment]
I will try to not add animation that can be added already with mods like ladder climbing (personality and NotEnoughAnimations)
the floating idle could be interesting. The mining animation would be a little problematic to recreate
