### ISSUE TITLE
Closest Eye + Eyebrow combo?

### ISSUE THREAD

**Issue by OptimalArchitect** [IthanMendoza/Fresh-Moves#42]
Trying to see what can I use already as a preset to get it as close as possible to the skin I want to use. 
![IMG_5303](https://github.com/IthanMendoza/Fresh-Moves/assets/92662837/5744ef8f-4683-4709-b4ca-882936f608dd)

![IMG_5308](https://github.com/IthanMendoza/Fresh-Moves/assets/92662837/8194357e-ee5b-4bf2-ba8c-f4dfa10af9b3)

or is there a way I can attempt to customize it to that exact eye and eyebrow combo?

**Comment by IthanMendoza** [comment]
I haven't seen that eye type Until now so I don't think I can help u with that
