### ISSUE TITLE
Feature Request: 2x1 Derp Eyes but for skins that look like pigs

### ISSUE THREAD

**Issue by KenKeystone** [IthanMendoza/Fresh-Moves#43]
for the derp eyes section, theres currently no option for derp eyes when it comes to skins like this. And so i wanted to know if theres plans to do it, and if its even possible
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/132592642/9ba2c69c-f5d3-4c1c-84a0-fd08d7c294dc)

**Comment by IthanMendoza** [comment]
Mob eyes will have their section in the skin in a future update
