### ISSUE TITLE
Feature Request: 3x3 eyes

### ISSUE THREAD

**Issue by scarletdemi** [IthanMendoza/Fresh-Moves#44]
![burenyuu](https://github.com/IthanMendoza/Fresh-Moves/assets/168306342/80edfb53-5c88-4329-8307-a84f318208d5)
it'd be great if there was a way to animate these gigantic goofy eyes.

**Comment by scarletdemi** [comment]
if that's too big then maybe 2x3 eyes like the enderman but one pixel taller

**Comment by IthanMendoza** [comment]
Yeah they are too big and I won't be adding too unique eye types. Mostly becuase I'm running out of space
