### ISSUE TITLE
Your can't use Just Expressions + Improved Animations

### ISSUE THREAD

**Issue by joao-carmassi** [IthanMendoza/Fresh-Moves#49]
If you use both and then sneaking  this happens:

![2024-05-12_23 28 12](https://github.com/IthanMendoza/Fresh-Moves/assets/90992816/d52af6ab-49bd-489f-9cb4-844d9837acb9)

**Comment by jessentyx** [comment]
same issue here, funnily enough, my entire body got yeeted away, guess i will have to use the whole fresh move package for now

![image](https://github.com/IthanMendoza/Fresh-Moves/assets/169708192/cad4f3b3-2a4d-4920-ba79-a2e683f41c64)

**Comment by IthanMendoza** [comment]
It's a known issue and doesn't seem to have a fix
