### ISSUE TITLE
Possible solution

### ISSUE THREAD

**Issue by Furballllllll** [IthanMendoza/Fresh-Moves#51]
I've seen that there are many eye feature requests and I think the main problem is the amount of space available on the skin. I might have a solution to this, but it will make it more complicated and I don't know how feasable it is.
![thingy](https://github.com/IthanMendoza/Fresh-Moves/assets/125389821/04e87cd9-b830-408d-8d63-b98f64922b00)
Above is an idea I had. There could be multiple texture mappings and it would dictate which one the skin used based on a single pixel that is a certain colour. Eg. red (use specific colour codes) is the current mapping, blue is a whole new array of eye shapes and positions. This could also fix the problem of skins not using a transparent background so it's a white smear when playing online.

I would like to know if this helps :)

**Comment by IthanMendoza** [comment]
Sorry but the eyes rn are just a bunch of bones and cubes (in the player model) that are always there, transparent, waiting to have a texture to become visible. I would have to transform Fresh Moves to a former mod to do that
