### ISSUE TITLE
Are these Enderman eyes or not as they are low + pixel around side

### ISSUE THREAD

**Issue by Pyro0TV** [IthanMendoza/Fresh-Moves#55]
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/141536178/3d705867-1f07-40fb-85c2-23999f74cbeb)
If they aren't (i assumed they werent) can there be support for (1)1x3 eyes and eyebrows someday that'd be sick

**Comment by redboi18** [comment]
Thats a good idea tbh maybe they could also do one like this
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/124214835/a6b85a31-295c-4486-8644-c20a9a0c4f22)

**Comment by redboi18** [comment]
so 2x3 eyes

**Comment by IthanMendoza** [comment]
Not possible at the moment and I won't add too unique eye types because I don't have enough space in the texture to use.
