### ISSUE TITLE
1x2 eyes not working

### ISSUE THREAD

**Issue by Zerks** [IthanMendoza/Fresh-Moves#57]
hey guys I've been trying to follow the guide for the 1x2 eyes for my skin yet to no avail, I was wondering if there was anything I could do to fix this issue?
![ETF_player_skin_printout](https://github.com/IthanMendoza/Fresh-Moves/assets/12805409/7a9ae208-61ec-4e8a-858a-9beb926adeb4)

**Comment by IthanMendoza** [comment]
Those eyelids are bugged at the moment. Will be fixed Soon™
