### ISSUE TITLE
my skins original eyebrows are still there

### ISSUE THREAD

**Issue by CaptainMirage** [IthanMendoza/Fresh-Moves#59]
so i was doing all the steps and it eventually worked, but then i realized I have something above my eyes and I looked closer and figured out that my original eyebrows are still there, they just move up and down with my eyes, its kinda disturbing too when its moving, I did the eyebrows setup in the 2nd layer and I will post the skin and some screenshots below, did I do it wrong or is something wrong with my mods?

- this is my 2 by 2 eyed skin screenshot
![2024-05-15_15 01 21](https://github.com/IthanMendoza/Fresh-Moves/assets/87281406/fc6c1ab9-1401-428f-8f9f-ebdb507ad24b)

- this is my 2 by 1 eyed skin screenshot
![2024-05-15_14 59 31](https://github.com/IthanMendoza/Fresh-Moves/assets/87281406/81c9aa06-49e2-43a1-8b55-ee5df955df00)

-----
- my skin for the 2 by 2
![2022_05_25_mirage-edit-20352725](https://github.com/IthanMendoza/Fresh-Moves/assets/87281406/aec757d5-066c-4265-a059-2d028c4b8c0a)

- my skin for the 2 by 1
![2021_09_22_mirage---apex-legends-18971225](https://github.com/IthanMendoza/Fresh-Moves/assets/87281406/0eda15f8-9d21-43e8-a3e6-dd0b72529695)

**Comment by IthanMendoza** [comment]
![330888985-0eda15f8-9d21-43e8-a3e6-dd0b72529695](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/9be00ae7-f307-4737-aaa5-5684d26a9f4c)

The eyebrow hiders were not in the right position try this png instead
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/127630637/da2f1464-0de3-4930-aee9-e83c461f2bdb)

**Comment by CaptainMirage** [comment]
> ![330888985-0eda15f8-9d21-43e8-a3e6-dd0b72529695](https://private-user-images.githubusercontent.com/127630637/332621194-9be00ae7-f307-4737-aaa5-5684d26a9f4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzMyNjcsIm5iZiI6MTcxNjczMjk2NywicGF0aCI6Ii8xMjc2MzA2MzcvMzMyNjIxMTk0LTliZTAwYWU3LWYzMDctNDczNy1hYWE1LTU2ODRkMjZhOWY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWQwYzRkOTIxMTEwYjgwNTNiMmE4ZjcxYjE0OTliNWNlYmI1MTM1OTVlN2ZlMTFhZWM5ZGM5YmU2NGZmNDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZfNZouH8XUa2HflWXWpjkMbBVmY-yN0GzLQKnzbWVAo)
> 
> The eyebrow hiders were not in the right position try this png instead ![image](https://private-user-images.githubusercontent.com/127630637/332621313-da2f1464-0de3-4930-aee9-e83c461f2bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzMyNjcsIm5iZiI6MTcxNjczMjk2NywicGF0aCI6Ii8xMjc2MzA2MzcvMzMyNjIxMzEzLWRhMmYxNDY0LTBkZTMtNDkzMC1hZWU5LWU4M2M0NjFmMmJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2RkMjY1MGNhNjZkY2U2MGI1ODFlZWI4MGYzYzBkN2FjNzI1MjBhMjg1MGY4Yzg0NTc3OWFjMDFiYTQ3YzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IdxIPqURiN4dLAoQbLokKucQ_mDdha8Mg1-InfEUfrw)

wait what about the other one?

**Comment by CaptainMirage** [comment]
i dont understand how the eyebrows work, cuz the way you did it for the 2by1 was they were there with only one pixel gap, do I just move the eyebrow hiders one pixel higher everywhere or what? the eyebrows wiki is a bit confusing, nice work tho! its hard to do eyes by itself

**Comment by CaptainMirage** [comment]
okay i think i got some understanding of the counting, the eyebrow hider goes up 2 pixels at a time for each pixel the eyes are higher, and the eyebrow itself goes 1 pixel at a time higher, is that correct? and if so then the way it works for the 2 by 2 is only 1 pixel at a time for both right? man u need to make a discord server @IthanMendoza
