### ISSUE TITLE
Feature Request: Shorter Eyelashes (2x2 Eyes)

### ISSUE THREAD

**Issue by EpicGamer42069Fortnite** [IthanMendoza/Fresh-Moves#6]
I'm currently using the "Eyelashes (2x2 Eyes)" feature, but I removed a pixel from the bottom to achieve a shorter eyelash look.

![image](https://github.com/IthanMendoza/Fresh-Moves/assets/148576913/b1c28f17-b965-4ba7-8d8c-67ef6d5c4700)
![example skin](https://github.com/IthanMendoza/Fresh-Moves/assets/148576913/232828f6-d317-48d1-8f5a-d7823cfdf47f)
![example skin_scaled up](https://github.com/IthanMendoza/Fresh-Moves/assets/148576913/2f519f0d-804a-426c-bca5-0f5dc7f884a2)

However, this is not perfect, as there are some visual glitches with this approach.

![looking straight up](https://github.com/IthanMendoza/Fresh-Moves/assets/148576913/e09bd592-3522-47d8-a1b6-389430668b97)
![under the face view](https://github.com/IthanMendoza/Fresh-Moves/assets/148576913/4a455dc4-a18d-445f-9864-e490fa491b04)

**Comment by IthanMendoza** [comment]
I'll add hiders to cover the red part

**Comment by IthanMendoza** [comment]
yeah its because its a single cube, so I may split them into 2 separate cubes
