### ISSUE TITLE
My eyes have black bars over them.,

### ISSUE THREAD

**Issue by flyinggoatman** [IthanMendoza/Fresh-Moves#7]
![flyinggoatman-replacement](https://github.com/IthanMendoza/Fresh-Moves/assets/3386066/51dbcfa2-a768-4134-a0bf-684bcf804559)

![image](https://github.com/IthanMendoza/Fresh-Moves/assets/3386066/b25906de-9561-437f-a39d-7c2b57e3b340)

![javaw_2B5eOOw3Er](https://github.com/IthanMendoza/Fresh-Moves/assets/3386066/084bd634-09a4-4385-85e9-b5919313574f)

Extra info: I'm using ATM9.

**Comment by tomi69lolxd** [comment]
same issue happened here

**Comment by flyinggoatman** [comment]
> same issue happened here

Are you using ATM9?

**Comment by flyinggoatman** [comment]
> same issue happened here

I fixed it!

under the Resource Packs section
click this icon next to done. Then go to  "Textures -> Player skin settings" then change "Allow skin transparency" to "All skins" 
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/3386066/1984b4dd-3a85-47e3-b643-adf48756b515)

**Comment by amykatname** [comment]
aint got that

**Comment by amykatname** [comment]
this entity features mod setting shit dumb as hell, need to go in .minecraft\config\entity_texture_features.json

**Comment by IthanMendoza** [comment]
Yeah its a little problematic
