### ISSUE TITLE
Adding Support for 2x3 Eyes at the bottom of the face?

### ISSUE THREAD

**Issue by CannedDumby** [IthanMendoza/Fresh-Moves#75]
Will there ever be support for these kind of eyes? I'd love to see it, frankly, but some things just can't work out sometimes lol.

![Dumbymodel](https://github.com/IthanMendoza/Fresh-Moves/assets/113647758/a2ea8b22-cd8f-4b67-b86b-fb870469a079)

**Comment by IthanMendoza** [comment]
A very unique type of eyes so its not probably be supported.
