### ISSUE TITLE
Flying Arrows & Unparented Arrows

### ISSUE THREAD

**Issue by Fyoncle** [IthanMendoza/Fresh-Moves#76]
Theres 2 seperate glitches for this, one is for the expressive, one is for the faceless.

## Expressive Glitch;
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/63975256/eacbc513-83a5-4b80-a83f-f32acd5aefe7)
Arrows fly when got shot multiple times, eyes probably count as a body part.

## Faceless Glitch;
![image](https://github.com/IthanMendoza/Fresh-Moves/assets/63975256/8deb881d-809f-433d-9545-4812f670d77c)
Arrows not flying above your head, but arrows doesnt follow your head, probably doesn't follow your body parts too.

**Comment by IthanMendoza** [comment]
Hi :v, I already put this issue in the Traben's discord :v

**Comment by Fyoncle** [comment]
Hey there @IthanMendoza! This issue has been fixed by EMF 2.2.5!
