### ISSUE TITLE
Broken eyelashes and eyes(2x2)

### ISSUE THREAD

**Issue by Lemosha** [IthanMendoza/Fresh-Moves#82]
**I did everything according to the instructions, there are no other texture packs. How can this be fixed?**
![Снимок экрана 2024-05-26 111000](https://github.com/IthanMendoza/Fresh-Moves/assets/170854867/20e1fabe-e753-41ff-bcdf-700cc939a50e)
![2024-05-26_11 09 35](https://github.com/IthanMendoza/Fresh-Moves/assets/170854867/78422ffc-f0bc-4f27-9839-3ee87028c41a)
![2024-05-26_11 09 40](https://github.com/IthanMendoza/Fresh-Moves/assets/170854867/41c22b68-1721-43a4-a55d-284cdb196fc9)

**Comment by BotinkiIsLove** [comment]
Наш слон

**Comment by Lemosha** [comment]
> Наш слон

Что?
