### ISSUE TITLE
outer 1x2 eyes?

### ISSUE THREAD

**Issue by Raezoasr** [IthanMendoza/Fresh-Moves#9]
my skin has 1x2 eyes that are 1 pixel off to the sides so the ones available dont really work 
![9be488dc4e5180075d08ccdcaef557531ba1b5c4](https://github.com/IthanMendoza/Fresh-Moves/assets/168912502/3ba63c52-32b3-46c4-a603-265f82314d87)
<img width="92" alt="Screenshot 2024-05-04 at 10 10 29" src="https://github.com/IthanMendoza/Fresh-Moves/assets/168912502/fd4935ce-35f3-47cc-9ce4-1b997df3cee0">

**Comment by IthanMendoza** [comment]
I'll take those in count.
